### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by SpaceLeft** [HellpMe/Lavalink-Heroku-24-7#3]
![Capture](https://user-images.githubusercontent.com/40790870/146634918-9cee25bb-6738-4dff-b5c9-580d9fe89aee.PNG)

**Comment by b-hdev** [comment]
Sorry for the delay in responding, I'll check what's going on.

**Comment by b-hdev** [comment]
I fixed the problems, as I could see it was the node-fetch version, but I don't have a cdn to upload the lavalink server to be downloaded, I'm fixing this problem but it might take a while.

**Comment by b-hdev** [comment]
Fixed.
